# Form implementation generated from reading ui file '.\todo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(359, 408)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_btn = QtWidgets.QPushButton(parent=self.centralwidget, clicked=lambda: self.add_it())
        self.add_btn.setGeometry(QtCore.QRect(20, 50, 101, 24))
        self.add_btn.setObjectName("add_btn")
        self.remove_btn = QtWidgets.QPushButton(parent=self.centralwidget, clicked=lambda: self.remove_it())
        self.remove_btn.setGeometry(QtCore.QRect(130, 50, 101, 24))
        self.remove_btn.setObjectName("remove_btn")
        self.clear_btn = QtWidgets.QPushButton(parent=self.centralwidget, clicked=lambda: self.clear_it())
        self.clear_btn.setGeometry(QtCore.QRect(240, 50, 101, 24))
        self.clear_btn.setObjectName("clear_btn")
        self.task_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.task_edit.setGeometry(QtCore.QRect(20, 20, 321, 22))
        self.task_edit.setObjectName("task_edit")
        self.task_list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.task_list.setGeometry(QtCore.QRect(20, 90, 321, 261))
        self.task_list.setObjectName("task_list")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 359, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    # Add todo
    def add_it(self):
        todo = self.task_edit.text()
        self.task_list.addItem(todo)
        self.task_edit.clear()
    # Remove todo
    def remove_it(self):
        selected = self.task_list.currentRow()
        # self.task_edit.setText(str(selected))
        self.task_list.takeItem(selected)
    # Clear all
    def clear_it(self):
        self.task_list.clear()
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BhvMonitor"))
        self.remove_btn.setText(_translate("MainWindow", "Remove"))
        self.add_btn.setText(_translate("MainWindow", "Add"))
        self.clear_btn.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
